version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.5.60
    restart: always
    volumes:
      - /Users/docker/mysql/data:/var/lib/mysql
      - /Users/docker/mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf

    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin






