version: "2"

services:
  mysql:
    container_name: mysql
    image: mysql:5.5.60
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    command: --max_allowed_packet=32505856
  solo:
    container_name: solo
    image: b3log/solo:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      RUNTIME_DB: "MYSQL"
      JDBC_USERNAME: "root"
      JDBC_PASSWORD: "adminadmin"
      JDBC_DRIVER: "com.mysql.jdbc.Driver"
      JDBC_URL: "jdbc:mysql://mysql:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC"
    command: --listen_port=8080 --server_port=80 --server_scheme=https --server_host=www.liumapp.com
  nginx: 
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d"
      - "/root/cert/:/etc/nginx/conf.d/liumapp.com"
      - "./nginx/www/:/var/www/"





